### ISSUE TITLE
TypeError observed in pycharm

### ISSUE THREAD

**Issue by tlambert03** [napari/superqt#5]
received this error report via email...

I had this error message on PyCharm. Nevertheless, it doesn't forbid the program to run.

```
Traceback (most recent call last):
 File "python3.7/site-packages/superqt/sliders/_generic_range_slider.py", line 150, in event
   update_styles_from_stylesheet(self)
 File "python3.7/site-packages/superqt/sliders/_range_style.py", line 267, in update_styles_from_stylesheet
   parent = parent.parent()
TypeError: 'Main' object is not callable
```

If it can help you, my configuration :
Python 3.7.5 (virtual environment from miniConda)
PyQt 5.15.2
Linux OpenSUSE 15.2

**Comment by tlambert03** [comment]
user responded via email, problem not in this library
